# Generated by Django 5.0.3 on 2024-03-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik_takip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mission', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('student_class', models.CharField(blank=True, max_length=50)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tc_number', models.CharField(max_length=11)),
                ('active', models.BooleanField(default=True)),
                ('points_collected', models.IntegerField(default=0)),
            ],
        ),
    ]
