# Generated by Django 5.0.3 on 2024-04-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik_takip', '0004_alter_member_group_eventattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('member', 'event')},
        ),
    ]
