# Generated by Django 5.0.6 on 2025-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik_takip', '0010_alter_project_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipstudent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='volunteeringstudent',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='undefined', max_length=100, verbose_name='Durum (Burslu/Gönüllü)'),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
